baseURL = "/"
title = "L Jagger"
theme = "beautifulhugo"

[Params]
  subtitle = "Sometimes I write things"
  logo = "img/avatar-icon.png"
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  comments = false

[Author]
 github = "leanne182x"
 linkedin = "leannejagger"
 stackoverflow = "users/1348844/leanne182x"
 twitter = "Leanne182x"

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 3